// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertInfo: typeof import('./.vitepress/components/alerts/AlertInfo.vue')['default']
    IconInfo: typeof import('./.vitepress/components/icons/IconInfo.vue')['default']
    LayoutsResponsive: typeof import('./.vitepress/components/layouts/LayoutsResponsive.vue')['default']
    LayoutsResponsiveExpanded: typeof import('./.vitepress/components/layouts/LayoutsResponsiveExpanded.vue')['default']
  }
}
